INSERT INTO HERO(HERO_ID, HERO_NAME)
VALUES(HERO_SEQ.NEXTVAL,'Ardan');

INSERT INTO HERO(HERO_ID, HERO_NAME)
VALUES(HERO_SEQ.NEXTVAL,'Ardan');

-- start of game history
-- game 1
INSERT INTO GAMES(GAME_ID, GAME_DATE)
VALUES(GAME_SEQ.NEXTVAL, SYSDATE);

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 10, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 30, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 70, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 230, 'N');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 30, 'N');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 130, 'N');

-- game 2
--Phinn, Rona, Ozo
--Fortress, Koshka, Skaarf
INSERT INTO GAMES(GAME_ID, GAME_DATE)
VALUES(GAME_SEQ.NEXTVAL, SYSDATE);

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 240, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 250, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 270, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 180, 'N');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 40, 'N');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 110, 'N');


-- won: kestrel, fortress, flicker
-- lost: glaive, taka, petal
INSERT INTO GAMES(GAME_ID, GAME_DATE)
VALUES(GAME_SEQ.NEXTVAL, SYSDATE);

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 190, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 180, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 610, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 50, 'N');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 30, 'N');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 120, 'N');

-- won: joule, skye, phinn
-- lost: fortress, glaive, celeste
INSERT INTO GAMES(GAME_ID, GAME_DATE)
VALUES(GAME_SEQ.NEXTVAL, SYSDATE);

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 140, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 280, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 240, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 180, 'N');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 50, 'N');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 260, 'N');

-- won: rona, ardan, ringo
-- lost: lance, kestrel, skaarf  
INSERT INTO GAMES(GAME_ID, GAME_DATE)
VALUES(GAME_SEQ.NEXTVAL, SYSDATE);

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 250, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 10, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 130, 'Y');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 220, 'N');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 190, 'N');

INSERT INTO GAME_HISTORY(GAME_HISTORY_ID, GAME_ID, HERO_ID, IS_VICTORY)
VALUES(GAME_HISTORY_SEQ.NEXTVAL, GAME_SEQ.CURRVAL, 110, 'N');

-- Get the game history
select game_history_id, game_id, GET_HERO_NAME(hero_id) hero_name, is_victory, created_date
from GAME_HISTORY;


-- Create a new GUI to suggest the best combination for a given 2 heroes based on history

-- Give the number of wins for 2 given heroes. on this example, Ardan and Taka is given
select hero_name, count(*)
from 
(select h.HERO_NAME
from  game_history gh, hero h,
    (select ghi.game_id
     from game_history ghi
     where ghi.hero_id = '10'-- Ardan
     and ghi.is_victory = 'Y') given1,
    (select ghi.game_id
     from game_history ghi
     where ghi.hero_id = '30'-- Ardan
     and ghi.is_victory = 'Y') given2     
where gh.hero_id = h.hero_id
and gh.game_id = given1.game_id
and given1.game_id = given2.game_id
and gh.is_victory = 'Y'
and gh.hero_id != '10' -- Ardan
and gh.hero_id != '30' -- Taka
order by gh.game_id, gh.is_victory desc
)
group by hero_name
order by 2 desc, 1;

-- Also show the number of loses for 2 given heroes
select hero_name, count(*)
from 
(select h.HERO_NAME
from  game_history gh, hero h,
    (select ghi.game_id
     from game_history ghi
     where ghi.hero_id = '10'-- Ardan
     and ghi.is_victory = 'N') given1,
    (select ghi.game_id
     from game_history ghi
     where ghi.hero_id = '30'-- Ardan
     and ghi.is_victory = 'N') given2     
where gh.hero_id = h.hero_id
and gh.game_id = given1.game_id
and given1.game_id = given2.game_id
and gh.is_victory = 'N'
and gh.hero_id != '10' -- Ardan
and gh.hero_id != '30' -- Taka
order by gh.game_id, gh.is_victory desc
)
group by hero_name
order by 2 desc, 1;
