-- Version 1 (1% ROI)
INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'URC',199.9,201.9,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'GLO',2354,2377,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'AP',45.05,45.5,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'PCOR',10.6,10.71,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'ALI',38.35,38.74,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'ALI',37.9,38.28,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'AC',839,847.39,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'MCP',3.76,3.8,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'NIKL',5.5,5.56,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'JGS',83.8,84.64,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'PCOR',10.26,10.36,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'FGEN',24.2,24.45,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'VITA',1.01,1.02,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'DMC',12.5,12.63,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'HVN',17.5,17.7,SYSDATE);

INSERT INTO BUY_SELL_STOCKS(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_SEQ.NEXTVAL,'VITA',1.0,1.01,SYSDATE);

-- Version 2 (3% ROI)

INSERT INTO BUY_SELL_STOCKS_V2(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_V2_SEQ.NEXTVAL,'PCOR',10.26,10.57,SYSDATE);

INSERT INTO BUY_SELL_STOCKS_V2(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_V2_SEQ.NEXTVAL,'VITA',0.98,1.01,SYSDATE);

INSERT INTO BUY_SELL_STOCKS_V2(ID, STOCK_SYMBOL, BUY_PRICE, SELL_PRICE, CREATED_DATE)
VALUES(BUY_SELL_STOCKS_V2_SEQ.NEXTVAL,'HVN',17.46,17.98,SYSDATE);


