CREATE TABLE BUY_SELL_STOCKS(
  id NUMBER,
	 stock_symbol VARCHAR2(10) NOT NULL,
	 BUY_PRICE NUMBER(11,4),
	 SELL_PRICE NUMBER(11,4),
	 IS_ENABLED CHAR(1) DEFAULT 'Y',
	 IS_DELETED CHAR(1) DEFAULT 'N',
	 CREATED_DATE DATE,
	 MODIFIED_DATE DATE,
   CONSTRAINT "BUY_SELL_STOCKS_PK" PRIMARY KEY ("ID") ENABLE
)
/

CREATE TABLE BUY_SELL_STOCKS_V2(
  id NUMBER,
	 stock_symbol VARCHAR2(10) NOT NULL,
	 BUY_PRICE NUMBER(11,4),
	 SELL_PRICE NUMBER(11,4),
	 IS_ENABLED CHAR(1) DEFAULT 'Y',
	 IS_DELETED CHAR(1) DEFAULT 'N',
	 CREATED_DATE DATE,
	 MODIFIED_DATE DATE,
   CONSTRAINT "BUY_SELL_STOCKS_V2_PK" PRIMARY KEY ("ID") ENABLE
)
/
