INSERT INTO MOST_ACTIVE_STOCKS(ID, STOCK_SYMBOL, LAST_TRADING_PRICE, CLOSING_DATE)
VALUES(most_active_stocks_seq.NEXTVAL,'AC',850,'21-JUN-16');

INSERT INTO MOST_ACTIVE_STOCKS(ID, STOCK_SYMBOL, LAST_TRADING_PRICE, CLOSING_DATE)
VALUES(most_active_stocks_seq.NEXTVAL,'MBT',89,'21-JUN-16');

INSERT INTO MOST_ACTIVE_STOCKS(ID, STOCK_SYMBOL, LAST_TRADING_PRICE, CLOSING_DATE)
VALUES(most_active_stocks_seq.NEXTVAL,'ALI',39.6,'21-JUN-16');

INSERT INTO MOST_ACTIVE_STOCKS(ID, STOCK_SYMBOL, LAST_TRADING_PRICE, CLOSING_DATE)
VALUES(most_active_stocks_seq.NEXTVAL,'TEL',2120,'21-JUN-16');

INSERT INTO MOST_ACTIVE_STOCKS(ID, STOCK_SYMBOL, LAST_TRADING_PRICE, CLOSING_DATE)
VALUES(most_active_stocks_seq.NEXTVAL,'GTCAP',1500,'21-JUN-16');

INSERT INTO MOST_ACTIVE_STOCKS(ID, STOCK_SYMBOL, LAST_TRADING_PRICE, CLOSING_DATE)
VALUES(most_active_stocks_seq.NEXTVAL,'JGS',85.8,'21-JUN-16');

INSERT INTO MOST_ACTIVE_STOCKS(ID, STOCK_SYMBOL, LAST_TRADING_PRICE, CLOSING_DATE)
VALUES(most_active_stocks_seq.NEXTVAL,'MPI',6.91,'21-JUN-16');

INSERT INTO MOST_ACTIVE_STOCKS(ID, STOCK_SYMBOL, LAST_TRADING_PRICE, CLOSING_DATE)
VALUES(most_active_stocks_seq.NEXTVAL,'SMPH',25.8,'21-JUN-16');

INSERT INTO MOST_ACTIVE_STOCKS(ID, STOCK_SYMBOL, LAST_TRADING_PRICE, CLOSING_DATE)
VALUES(most_active_stocks_seq.NEXTVAL,'BDO',110,'21-JUN-16');

INSERT INTO MOST_ACTIVE_STOCKS(ID, STOCK_SYMBOL, LAST_TRADING_PRICE, CLOSING_DATE)
VALUES(most_active_stocks_seq.NEXTVAL,'MEG',4.51,'21-JUN-16');
