CREATE TABLE INC_TOPICS(
  topic_id NUMBER,
  topic_description VARCHAR2(24) NOT NULL,
  created_date DATE DEFAULT SYSDATE,
  modified_date DATE,
  CONSTRAINT "HERO_PK" PRIMARY KEY ("HERO_ID") ENABLE
)
/

CREATE TABLE INC_VERSES(
  inc_verse_id NUMBER,
  book_version_id, 
  book_list_id,
  book_chapter_id,
  book_verse_id,
  created_date DATE,
  modified_date DATE,
  topic_id
  CONSTRAINT "HERO_PK" PRIMARY KEY ("HERO_ID") ENABLE
)
/


CREATE TABLE BOOK_VERSION(
BOOK_VERSION_ID NUMBER,
VERSION_NAME VARCHAR2(100),
CONSTRAINT BOOK_VERSION_PK PRIMARY KEY (BOOK_VERSION_ID)
)
/

CREATE TABLE BOOK_LIST (
BOOK_LIST_ID NUMBER,
BOOK_NAME VARCHAR2(100),
IS_NEW_TESTAMENT CHAR(1),
BOOK_CHAPTER_START NUMBER,
BOOK_CHAPTER_END NUMBER,
CONSTRAINT BOOK_LIST_PK PRIMARY KEY (BOOK_LIST_ID)
)
/

CREATE TABLE BOOK_CHAPTER (
BOOK_CHAPTER_ID NUMBER,
BOOK_LIST_ID NUMBER,
CHAPTER_NUMBER NUMBER,
VERSE_START NUMBER,
VERSE_END NUMBER,
CONSTRAINT BOOK_CHAPTER_PK PRIMARY KEY (BOOK_CHAPTER_ID),
CONSTRAINT BOOK_CHAPTER_FK FOREIGN KEY (BOOK_LIST_ID) REFERENCES BOOK_LIST(BOOK_LIST_ID)
)
/

CREATE TABLE BOOK_VERSE (
BOOK_VERSE_ID NUMBER,
BOOK_VERSION_ID NUMBER,
BOOK_CHAPTER_ID NUMBER,
VERSE_NUMBER NUMBER,
VERSE_MESSAGE VARCHAR2(512),
CONSTRAINT BOOK_VERSE_PK PRIMARY KEY (VERSE_ID),
CONSTRAINT BOOK_VERSE_FK1 FOREIGN KEY (BOOK_VERSION_ID) REFERENCES BOOK_VERSION(BOOK_VERSION_ID),
CONSTRAINT BOOK_VERSE_FK2 FOREIGN KEY (BOOK_CHAPTER_ID) REFERENCES BOOK_CHAPTER(BOOK_CHAPTER_ID)
)
/




CREATE TABLE ARDAN_GAME_HISTORY(
  ARDAN_VICTORY_HISTORY_ID NUMBER,
  ally1_hero_id NUMBER NOT NULL,
  ally2_hero_id NUMBER NOT NULL,
  enemy1_hero_id NUMBER NOT NULL,
  enemy2_hero_id NUMBER NOT NULL,
  enemy3_hero_id NUMBER NOT NULL,
  is_victory CHAR(1) NOT NULL,
  created_date DATE DEFAULT SYSDATE,
  modified_date DATE,
  CONSTRAINT "ARDAN_VICTORY_HISTORY_PK" PRIMARY KEY ("ARDAN_VICTORY_HISTORY_ID") ENABLE,
  CONSTRAINT ARDAN_VICTORY_HISTORY_FK1 FOREIGN KEY (ALLY1_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT ARDAN_VICTORY_HISTORY_FK2 FOREIGN KEY (ALLY2_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT ARDAN_VICTORY_HISTORY_FK3 FOREIGN KEY (ENEMY1_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT ARDAN_VICTORY_HISTORY_FK4 FOREIGN KEY (ENEMY2_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT ARDAN_VICTORY_HISTORY_FK5 FOREIGN KEY (ENEMY3_HERO_ID) REFERENCES HERO(HERO_ID)
)
/

CREATE TABLE ADAGIO_GAME_HISTORY(
  ADAGIO_VICTORY_HISTORY_ID NUMBER,
  ally1_hero_id NUMBER NOT NULL,
  ally2_hero_id NUMBER NOT NULL,
  enemy1_hero_id NUMBER NOT NULL,
  enemy2_hero_id NUMBER NOT NULL,
  enemy3_hero_id NUMBER NOT NULL,
  is_victory CHAR(1) NOT NULL,
  created_date DATE DEFAULT SYSDATE,
  modified_date DATE,
  CONSTRAINT "ADAGIO_VICTORY_HISTORY_PK" PRIMARY KEY ("ADAGIO_VICTORY_HISTORY_ID") ENABLE,
  CONSTRAINT ADAGIO_VICTORY_HISTORY_FK1 FOREIGN KEY (ALLY1_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT ADAGIO_VICTORY_HISTORY_FK2 FOREIGN KEY (ALLY2_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT ADAGIO_VICTORY_HISTORY_FK3 FOREIGN KEY (ENEMY1_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT ADAGIO_VICTORY_HISTORY_FK4 FOREIGN KEY (ENEMY2_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT ADAGIO_VICTORY_HISTORY_FK5 FOREIGN KEY (ENEMY3_HERO_ID) REFERENCES HERO(HERO_ID)
)
/

CREATE TABLE CATHERINE_GAME_HISTORY(
  CATHERINE_VICTORY_HISTORY_ID NUMBER,
  ally1_hero_id NUMBER NOT NULL,
  ally2_hero_id NUMBER NOT NULL,
  enemy1_hero_id NUMBER NOT NULL,
  enemy2_hero_id NUMBER NOT NULL,
  enemy3_hero_id NUMBER NOT NULL,
  is_victory CHAR(1) NOT NULL,
  created_date DATE DEFAULT SYSDATE,
  modified_date DATE,
  CONSTRAINT "CATHERINE_VICTORY_HISTORY_PK" PRIMARY KEY ("CATHERINE_VICTORY_HISTORY_ID") ENABLE,
  CONSTRAINT CATHERINE_VICTORY_HISTORY_FK1 FOREIGN KEY (ALLY1_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT CATHERINE_VICTORY_HISTORY_FK2 FOREIGN KEY (ALLY2_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT CATHERINE_VICTORY_HISTORY_FK3 FOREIGN KEY (ENEMY1_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT CATHERINE_VICTORY_HISTORY_FK4 FOREIGN KEY (ENEMY2_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT CATHERINE_VICTORY_HISTORY_FK5 FOREIGN KEY (ENEMY3_HERO_ID) REFERENCES HERO(HERO_ID)
)
/

CREATE TABLE LANCE_GAME_HISTORY(
  LANCE_VICTORY_HISTORY_ID NUMBER,
  ally1_hero_id NUMBER NOT NULL,
  ally2_hero_id NUMBER NOT NULL,
  enemy1_hero_id NUMBER NOT NULL,
  enemy2_hero_id NUMBER NOT NULL,
  enemy3_hero_id NUMBER NOT NULL,
  is_victory CHAR(1) NOT NULL,
  created_date DATE DEFAULT SYSDATE,
  modified_date DATE,
  CONSTRAINT "LANCE_VICTORY_HISTORY_PK" PRIMARY KEY ("LANCE_VICTORY_HISTORY_ID") ENABLE,
  CONSTRAINT LANCE_VICTORY_HISTORY_FK1 FOREIGN KEY (ALLY1_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT LANCE_VICTORY_HISTORY_FK2 FOREIGN KEY (ALLY2_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT LANCE_VICTORY_HISTORY_FK3 FOREIGN KEY (ENEMY1_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT LANCE_VICTORY_HISTORY_FK4 FOREIGN KEY (ENEMY2_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT LANCE_VICTORY_HISTORY_FK5 FOREIGN KEY (ENEMY3_HERO_ID) REFERENCES HERO(HERO_ID)
)
/

CREATE TABLE LYRA_GAME_HISTORY(
  LYRA_VICTORY_HISTORY_ID NUMBER,
  ally1_hero_id NUMBER NOT NULL,
  ally2_hero_id NUMBER NOT NULL,
  enemy1_hero_id NUMBER NOT NULL,
  enemy2_hero_id NUMBER NOT NULL,
  enemy3_hero_id NUMBER NOT NULL,
  is_victory CHAR(1) NOT NULL,
  created_date DATE DEFAULT SYSDATE,
  modified_date DATE,
  CONSTRAINT "LYRA_VICTORY_HISTORY_PK" PRIMARY KEY ("LYRA_VICTORY_HISTORY_ID") ENABLE,
  CONSTRAINT LYRA_VICTORY_HISTORY_FK1 FOREIGN KEY (ALLY1_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT LYRA_VICTORY_HISTORY_FK2 FOREIGN KEY (ALLY2_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT LYRA_VICTORY_HISTORY_FK3 FOREIGN KEY (ENEMY1_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT LYRA_VICTORY_HISTORY_FK4 FOREIGN KEY (ENEMY2_HERO_ID) REFERENCES HERO(HERO_ID),
  CONSTRAINT LYRA_VICTORY_HISTORY_FK5 FOREIGN KEY (ENEMY3_HERO_ID) REFERENCES HERO(HERO_ID)
)
/

-- Get the latest entry for Ardan
select ardan.ardan_victory_history_id, ally1.hero_name, ally2.hero_name, ardan.is_victory
from ARDAN_GAME_HISTORY ardan, HERO ally1, HERO ally2
where ardan.ally1_hero_id = ally1.hero_id
and ardan.ally2_hero_id = ally2.hero_id
and ardan.is_victory = 'Y'
order by ardan.ardan_victory_history_id desc;
