CREATE TABLE BOOK_VERSION(
BOOK_VERSION_ID NUMBER,
VERSION_NAME VARCHAR2(100),
CONSTRAINT BOOK_VERSION_PK PRIMARY KEY (BOOK_VERSION_ID)
)
/

CREATE TABLE BOOK_LIST (
BOOK_LIST_ID NUMBER,
BOOK_NAME VARCHAR2(100),
IS_NEW_TESTAMENT CHAR(1),
BOOK_CHAPTER_END NUMBER,
CONSTRAINT BOOK_LIST_PK PRIMARY KEY (BOOK_LIST_ID)
)
/

CREATE TABLE BOOK_CHAPTER (
BOOK_CHAPTER_ID NUMBER,
BOOK_LIST_ID NUMBER,
CHAPTER_NUMBER NUMBER,
VERSE_END NUMBER,
CONSTRAINT BOOK_CHAPTER_PK PRIMARY KEY (BOOK_CHAPTER_ID),
CONSTRAINT BOOK_CHAPTER_FK FOREIGN KEY (BOOK_LIST_ID) REFERENCES BOOK_LIST(BOOK_LIST_ID)
)
/

CREATE TABLE BOOK_VERSE (
VERSE_ID NUMBER,
BOOK_VERSION_ID NUMBER,
BOOK_CHAPTER_ID NUMBER,
VERSE_NUMBER NUMBER,
VERSE_MESSAGE VARCHAR2(512),
CONSTRAINT BOOK_VERSE_PK PRIMARY KEY (VERSE_ID),
CONSTRAINT BOOK_VERSE_FK1 FOREIGN KEY (BOOK_VERSION_ID) REFERENCES BOOK_VERSION(BOOK_VERSION_ID),
CONSTRAINT BOOK_VERSE_FK2 FOREIGN KEY (BOOK_CHAPTER_ID) REFERENCES BOOK_CHAPTER(BOOK_CHAPTER_ID)
)
/

CREATE TABLE INC_TEACHINGS(
TEACHING_ID NUMBER,
ABOUT VARCHAR2(1000),
CONSTRAINT INC_TEACHINGS_PK PRIMARY KEY (TEACHING_ID)
)
/

CREATE TABLE INC_TEACHING_DETAILS (
DETAIL_ID NUMBER,
TEACHING_ID NUMBER,
BOOK_VERSION_ID NUMBER,
BOOK_CHAPTER_ID NUMBER,
VERSE_REF_START NUMBER,
VERSE_REF_END NUMBER,
CONSTRAINT INC_TEACHING_DETAILS_PK PRIMARY KEY (DETAIL_ID),
CONSTRAINT INC_TEACHING_DETAILS_FK1 FOREIGN KEY (TEACHING_ID) REFERENCES INC_TEACHINGS(TEACHING_ID),
CONSTRAINT INC_TEACHING_DETAILS_FK2 FOREIGN KEY (BOOK_VERSION_ID) REFERENCES BOOK_VERSION(BOOK_VERSION_ID),
CONSTRAINT INC_TEACHING_DETAILS_FK3 FOREIGN KEY (BOOK_CHAPTER_ID) REFERENCES BOOK_CHAPTER(BOOK_CHAPTER_ID)
)
/

CREATE TABLE BEN_LESSONS_LEARNED (
LEARN_ID NUMBER,
TEACHING_ID NUMBER,
LESSON_DATE DATE,
CONSTRAINT BEN_LESSONS_LEARNED_PK PRIMARY KEY (LEARN_ID),
CONSTRAINT BEN_LESSONS_LEARNED_FK FOREIGN KEY (TEACHING_ID) REFERENCES INC_TEACHINGS(TEACHING_ID)
)
/
