INSERT INTO BEN_LESSONS_LEARNED(LEARN_ID, TEACHING_ID, LESSON_DATE)
VALUES(BEN_LESSONS_LEARNED_SEQ.NEXTVAL,1,current_date);

INSERT INTO BEN_LESSONS_LEARNED(LEARN_ID, TEACHING_ID, LESSON_DATE)
VALUES(BEN_LESSONS_LEARNED_SEQ.NEXTVAL,2,current_date);

INSERT INTO BEN_LESSONS_LEARNED(LEARN_ID, TEACHING_ID, LESSON_DATE)
VALUES(BEN_LESSONS_LEARNED_SEQ.NEXTVAL,3,current_date);
