INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Genesis','N',50);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Exodus','N',40);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Leviticus','N',27);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Numbers','N',36);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Deuteronomy','N',34);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Joshua','N',24);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Judges','N',21);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Ruth','N',4);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'1 Samuel','N',31);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'2 Samuel','N',24);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'1 Kings','N',22);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'2 Kings','N',25);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'1 Chronicles','N',29);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'2 Chronicles','N',36);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Ezra','N',10);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Nehemiah','N',13);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Esther','N',10);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Job','N',42);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Psalm','N',150);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Proverbs','N',31);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Ecclesiastes','N',12);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Song of Songs','N',8);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Isaiah','N',66);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Jeremiah','N',52);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Lamentations','N',5);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Ezekiel','N',48);







INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'Romans','Y',16);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'1 Timothy','Y',6);

INSERT INTO BOOK_LIST(BOOK_LIST_ID,BOOK_NAME,IS_NEW_TESTAMENT,BOOK_CHAPTER_END)
VALUES(BOOK_LIST_SEQ.NEXTVAL,'James','Y',5);