INSERT INTO INC_TEACHINGS(TEACHING_ID, ABOUT)
VALUES(INC_TEACHINGS_SEQ.NEXTVAL,'Human''s Biggest Problem');

INSERT INTO INC_TEACHINGS(TEACHING_ID, ABOUT)
VALUES(INC_TEACHINGS_SEQ.NEXTVAL,'Monetary Offerings And Sharing Of Faith');

INSERT INTO INC_TEACHINGS(TEACHING_ID, ABOUT)
VALUES(INC_TEACHINGS_SEQ.NEXTVAL,'Test Of Faith: Be Glad When You Encounter Trials');

