INSERT INTO INC_TEACHING_DETAILS(DETAIL_ID,TEACHING_ID,BOOK_VERSION_ID,BOOK_CHAPTER_ID,VERSE_REF_START,VERSE_REF_END)
VALUES(INC_TEACHING_DETAILS_SEQ.NEXTVAL,1,1,1,24,24);

INSERT INTO INC_TEACHING_DETAILS(DETAIL_ID,TEACHING_ID,BOOK_VERSION_ID,BOOK_CHAPTER_ID,VERSE_REF_START,VERSE_REF_END)
VALUES(INC_TEACHING_DETAILS_SEQ.NEXTVAL,2,1,2,18,19);

INSERT INTO INC_TEACHING_DETAILS(DETAIL_ID,TEACHING_ID,BOOK_VERSION_ID,BOOK_CHAPTER_ID,VERSE_REF_START,VERSE_REF_END)
VALUES(INC_TEACHING_DETAILS_SEQ.NEXTVAL,3,1,3,2,8);
