INSERT INTO BOOK_VERSION (BOOK_VERSION_ID,VERSION_NAME)
VALUES(BOOK_VERSION_SEQ.NEXTVAL,'New International Version (NIV)');

INSERT INTO BOOK_VERSION (BOOK_VERSION_ID,VERSION_NAME)
VALUES(BOOK_VERSION_SEQ.NEXTVAL,'King James Version (KJV)');

