INSERT INTO BOOK_CHAPTER(BOOK_CHAPTER_ID, BOOK_LIST_ID, CHAPTER_NUMBER, VERSE_END)
VALUES(BOOK_CHAPTER_SEQ.NEXTVAL,16,7,25);

INSERT INTO BOOK_CHAPTER(BOOK_CHAPTER_ID, BOOK_LIST_ID, CHAPTER_NUMBER, VERSE_END)
VALUES(BOOK_CHAPTER_SEQ.NEXTVAL,17,6,21);

INSERT INTO BOOK_CHAPTER(BOOK_CHAPTER_ID, BOOK_LIST_ID, CHAPTER_NUMBER, VERSE_END)
VALUES(BOOK_CHAPTER_SEQ.NEXTVAL,29,1,27);
